/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PrimeAutoComplete: typeof import('primevue/autocomplete')['default']
    PrimeAvatar: typeof import('primevue/avatar')['default']
    PrimeBadge: typeof import('primevue/badge')['default']
    PrimeMenu: typeof import('primevue/menu')['default']
    PrimeMenubar: typeof import('primevue/menubar')['default']
    PrimeProgressBar: typeof import('primevue/progressbar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
