query FestivalClassSearch($festivalClassSearch: FestivalClassSearchArgs!) {
  festivalClassSearch(festivalClassSearch: $festivalClassSearch) {
    id
    classNumber
    maxSelections
    minSelections
    requiredSelection
    performerType
    price
    subdiscipline {
      name
    }
    level {
      name
    }
    category {
      name
    }
    trophies {
      id
      name
      description
    }
  }
}
