query CommunityGroupInfo($registrationId: Int!) {
  registration(id: $registrationId) {
    community {
      communityGroups {
        id
        name
        groupSize
        chaperones
        wheelchairs
        earliestTime
        latestTime
        unavailable
        conflictPerformers
      }
    }
  }
}
