query CommunityInfo($registrationId: Int!) {
  registration(id: $registrationId) {
    community {
      id
      name
      streetNumber
      streetName
      city
      province
      postalCode
      phone
      email
    }
  }
}
