query FieldConfig($fieldName: String!, $tableName: String!) {
  fieldConfig(fieldName: $fieldName, tableName: $tableName) {
    id
    tableName
    fieldName
    customField
    customFieldType
    submissionRequired
    __typename
  }
}
