query FormError($registrationId: Int, $formErrorId: Int) {
  formError(formErrorID: $formErrorId, registrationID: $registrationId) {
    id
    classErrors
    communityInfoErrors
    communityTeacherErrors
    groupInfoErrors
    groupPerformersErrors
    groupTeacherErrors
    schoolGroupErrors
    schoolGroupsErrors
    schoolInfoErrors
    schoolTeacherErrors
    soloPerformerErrors
    soloTeacherErrors
    __typename
  }
}
