query MyUser {
  myUser {
    id
    firstName
    lastName
    apartment
    streetNumber
    streetName
    city
    province
    postalCode
    phone
    email
    emailConfirmed
    instrument
    privateTeacher
    schoolTeacher
    hasSignedIn
  }
}
