query Performers($registrationId: Int!) {
  performers(registrationID: $registrationId) {
    id
    firstName
    lastName
    age
    apartment
    streetNumber
    streetName
    city
    province
    postalCode
    phone
    email
    instrument
    level
  }
}
