query Performers($registrationId: Int!) {
  performers(registrationID: $registrationId) {
    id
    pronouns
    firstName
    lastName
    age
    address
    city
    province
    postalCode
    phone
    email
    instrument
    level
    otherClasses
    unavailable
    photoPermission
  }
}
