query Registrations($performerType: PerformerType) {
  registrations(performerType: $performerType) {
    id
    createdAt
    label
    performerType
    submittedAt
    payedAmt
    totalAmt
    transactionInfo
    confirmation
    updatedAt
  }
}
