query Registrations($performerType: PerformerType) {
  registrations(performerType: $performerType) {
    id
    confirmation
    label
    payedAmt
    performerType
    submittedAt
    teacher {
      id
    }
    totalAmt
    transactionInfo
    createdAt
    updatedAt
    user {
      firstName
      lastName
      email
    }
  }
}
