query RegisteredClasses($registrationId: Int!) {
  registration(id: $registrationId) {
    registeredClasses {
      category
      classType
      classNumber
      discipline
      id
      level
      minSelections
      maxSelections
      numberOfSelections
      price
      subdiscipline
      schoolGroupID
      communityGroupID
      selections {
        composer
        duration
        id
        largerWork
        movement
        title
      }
    }
  }
}
