query SubdisciplinesByType(
  $categoryId: Int!
  $disciplineId: Int!
  $levelId: Int!
  $performerType: PerformerType!
) {
  subdisciplines(
    categoryID: $categoryId
    disciplineID: $disciplineId
    levelID: $levelId
    performerType: $performerType
  ) {
    id
    name
    description
    maxPerformers
    minPerformers
    performerType
  }
}
