query TeacherInfo($teacherID: Int!) {
  teacher(teacherID: $teacherID) {
    id
    prefix
    firstName
    lastName
    apartment
    streetNumber
    streetName
    city
    province
    postalCode
    phone
    email
    instrument
  }
}
