query AllTeachersSearch($privateTeacher: Boolean!, $schoolTeacher: Boolean!) {
  teachers(privateTeacher: $privateTeacher, schoolTeacher: $schoolTeacher) {
    id
    firstName
    lastName
    instrument
  }
}
