/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PVAutoComplete: typeof import('primevue/autocomplete')['default']
    PVAvatar: typeof import('primevue/avatar')['default']
    PVBadge: typeof import('primevue/badge')['default']
    PVButton: typeof import('primevue/button')['default']
    PVCalendar: typeof import('primevue/calendar')['default']
    PVCard: typeof import('primevue/card')['default']
    PVColumn: typeof import('primevue/column')['default']
    PVDataTable: typeof import('primevue/datatable')['default']
    PVDatePicker: typeof import('primevue/datepicker')['default']
    PVDialog: typeof import('primevue/dialog')['default']
    PVDrawer: typeof import('primevue/drawer')['default']
    PVEditor: typeof import('primevue/editor')['default']
    PVIconField: typeof import('primevue/iconfield')['default']
    PVInputIcon: typeof import('primevue/inputicon')['default']
    PVInputMask: typeof import('primevue/inputmask')['default']
    PVInputNumber: typeof import('primevue/inputnumber')['default']
    PVInputText: typeof import('primevue/inputtext')['default']
    PVMenu: typeof import('primevue/menu')['default']
    PVMenubar: typeof import('primevue/menubar')['default']
    PVProgressBar: typeof import('primevue/progressbar')['default']
    PVSplitButton: typeof import('primevue/splitbutton')['default']
    PVToolbar: typeof import('primevue/toolbar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
