query MyUser {
  myUser {
    id
    firstName
    lastName
    address
    city
    province
    postalCode
    phone
    email
    emailConfirmed
    instrument
    privateTeacher
    schoolTeacher
    isActive
  }
}
