query SubdisciplinesByType(
  $disciplineId: Int!
  $performerType: PerformerType!
) {
  subdisciplines(disciplineID: $disciplineId, performerType: $performerType) {
    id
    name
    description
    maxPerformers
    minPerformers
    performerType
  }
}
