query TeacherInfo($teacherID: Int, $teacherEmail: String) {
  teacher(teacherID: $teacherID, teacherEmail: $teacherEmail) {
    id
    firstName
    lastName
    address
    city
    province
    postalCode
    phone
    email
    instrument
  }
}
